### ISSUE TITLE
bug: unable to implement on android device

### ISSUE THREAD

**Issue by rahul-chefkart** [capacitor-community/firebase-crashlytics#54] opened 2021-12-15 11:35 UTC
**Plugin version:**
Crashlytics gradle version - 'com.google.firebase:firebase-crashlytics-gradle:2.8.1',
Android gradle version - 'com.android.tools.build:gradle:4.2.2',
Firebase Bom version - 'com.google.firebase:firebase-bom:29.0.2'
Firebase Core version - 'com.google.firebase:firebase-core:17.5.0'
firebaseCrashlyticsVersion - '18.1.0'
npm package - "@capacitor-community/firebase-crashlytics": "^1.2.0"

**Platform(s):**
Android

**Current behavior:**
App is closing automatically just after the splash screen after implementing the firebase Crashlytics.

**Expected behavior:**
App must use the force crash method and must send the report to the firebase crashlytics console.

**Steps to reproduce:**
Install all the dependencies with the versions mentioned above.

**Related code:**

Exactly followed the steps provided in docs.

**Capacitor doctor:**

Latest Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by sultanatif344** [comment] 2021-12-15 12:04
Were you able to resolve this issue? I am having the same problem.

**Comment by robingenz** [comment] 2021-12-15 12:15
Hi @rahul-chefkart,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by HaileyGu** [comment] 2021-12-18 08:06
Hi, you can see the log when you enable firebase to debug mode.
I observed behavior that is reported on this issue, and the reason on the console was `The Crashlytics build ID is missing.`.

I added `classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'` on top-level gradle.(`${your-project}/android/build.gradle`) and then the issue is resolved.

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1' // to prevent 'The Crashlytics build ID is missing.' error

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by therahulchoudhary** [comment] 2021-12-21 05:16
Hello @HaileyGu Please find the build.gradle of my project.

`
buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
And package.json contains this version:-
`"@capacitor-community/firebase-crashlytics": "^1.2.0",`

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

and app level build.gradle is given below:-
`dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
    implementation platform('com.google.firebase:firebase-bom:29.0.3')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
}

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
        apply plugin: 'com.google.firebase.crashlytics'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by therahulchoudhary** [comment] 2021-12-21 05:34
> Hi @rahul-chefkart, thank you for your request. Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

@robingenz  I have tried creating a whole new project and in that project, everything was working fine for both android and iOS.

But for my project getting this error  **""FirebaseCrashlytics" plugin is not implemented on android"** on trigger the crash method.

**Comment by robingenz** [comment] 2021-12-21 07:48
This message usually appears when the [installation instructions](https://github.com/capacitor-community/firebase-crashlytics#installation) have not been followed correctly.
Please make sure you follow each step correctly.

If you have recently updated from Capacitor 2, make sure that the plugin is not registered in the `MainActivity.java`.

Make sure you run `npx cap sync`.

**Comment by kidGodzilla** [comment] 2022-01-18 00:21
Also getting the issue.

Cordova CLI	10.0.0
Ionic CLI	6.18.0
Node.js	16.13.0
Node.js versions	12.22.7 / 14.18.1 / 16.13.0
npm	8.1.0
Yarn	1.22.17
Python	3
Debian	11.1
Gradle	4.3.1
OpenJDK	1.8.0_265 and 11.0.12
Android SDK	27-31

Building inside of ionicframework.com fail on native device. Issues with logcat, so when moving to Android studio the debug becomes:

```
E/FirebaseCrashlytics: .
    .     |  | 
    .     |  |
    .     |  |
    .   \ |  | /
    .    \    /
    .     \  /
    .      \/
    .
    The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
    .
    .      /\
    .     /  \
    .    /    \
    .   / |  | \
    .     |  |
    .     |  |
    .     |  |
    .
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: next.....com, PID: 11305
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:7392)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6904)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6675)
        at android.app.ActivityThread.access$1500(ActivityThread.java:249)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:125)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:142)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:58)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
        at com.google.firebase.crashlytics.-$$Lambda$CrashlyticsRegistrar$Pfd5XmDCFzNyAT9o9H6rDnTBQE4.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:132)
        at com.google.firebase.components.-$$Lambda$ComponentRuntime$4FqOW9eOQsvFYo-HpMfxCOnPQr0.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7387)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6904) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6675) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:249) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
I/Process: Sending signal. PID: 11305 SIG: 9
Disconnected from the target VM, address: 'localhost:50393', transport: 'socket'
```

I found a relevant issue in another project.  

https://github.com/xamarin/XamarinComponents/issues/956

> From Firebase source:

> https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java#L110

> https://github.com/firebase/firebase-android-sdk/blob/aa3c89f5217a72d83a55f771d1ad5a12483f9aaf/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L805

> It seems new Crashlytics SDK depends on "mapping file" resource id being available at runtime (I'm guessing generated by gradle?).

Suggested adding this to strings.xml, which worked:

```
<string name="com.google.firebase.crashlytics.mapping_file_id">none</string>
```

I went through your demo project pretty thoroughly and that was the only change I needed to make. Didn't see it on your demo project though:
https://github.com/robingenz/capacitor-firebase-plugin-demo/blob/main/android/app/src/main/res/values/strings.xml

**Comment by robingenz** [comment] 2022-01-18 08:42
Hi @kidGodzilla,
please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so that I can reproduce the problem.
This problem does not occur in my demo app.

**Closed as completed** 2022-02-18 00:32 UTC
Labels: needs: reproduction
