### ISSUE TITLE
firebase crashlytics  not working 

### ISSUE THREAD

**Issue by essujith** [capacitor-community/firebase-crashlytics#2] opened 2019-10-21 13:10 UTC
Hi,

I installed capacitor-crashlytics , npm install --save capacitor-crashlytics,trying to track the crashlytics but its not showing in firebase crashlytics  account,can you help on this how to integrate using capacitor

**Comment by SteysiCenteno** [comment] 2019-11-22 00:12
I have the same problem @essujith :(

**Comment by Camiloess** [comment] 2020-06-27 02:20
I was having the same problem, it seems like it only shows errors after calling FirebaseCrashlytic.crash(); and open again the app, but I didn't find a way to record a non-fatal error....

**Comment by stewones** [comment] 2020-06-28 17:11
Have you activated debug view? Real Crashlytics data can take a while to appear. 

Also the public api has been changed but it’s still undocumented, please check readme for the actual api and make necessary changes in your code.

**Comment by priyankpat** [comment] 2020-06-30 14:30
To add to @stewwan's answer, please take a look at [enabling debug logging](https://github.com/capacitor-community/firebase-crashlytics#enable-crashlytics-debug-logging) to further debug your problem.

**Comment by SalahAdDin** [comment] 2020-12-23 09:19
Well, today 23 December i can't get the logs from my application, and i think it is because [of](https://firebase.google.com/docs/guides?authuser=0):

> Fabric shutdown: The legacy Fabric SDK and old versions of the Firebase Crashlytics SDK are now deprecated and will no longer report your app's crashes starting November 15, 2020. If you migrated your app from Fabric and want to continue getting crash reports in the Firebase console, visit the upgrade guide and make sure you're using Firebase Crashlytics SDK version 17.0.0+ for Android, 4.0.0+ for iOS, or 6.15.0+ for Unity.

@priyankpat @danielprrazevedo are you aware of this?

**Comment by tnoetzel** [comment] 2020-12-24 17:47
@SalahAdDin - After playing with this for a bit, I can confirm that this package _does_ work for iOS and that it is *NOT* using the deprecated Fabric SDK.

If you go into `node_modules/@capacitor-community/firebase-crashlytics/ios/` and look at the `Podfile.lock` version, you can see the version of FirebaseCrashlytics in use. For me it's `4.2.0` which is greater than the minimum 4.0.0 required.

To get it to work on my dev build, I had to do the following:

1. Enable dSYM file generation for debug builds in XCode: In project navigator click on App; then click on "Build Settings"; under Build Options make sure Debug Information Format is set to `DWARF with dSYM File`

2. Upload dSYM files to Crashlytics by running `/path/to/pods/directory/FirebaseCrashlytics/upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs`

The path to upload-symbols, relative to your root project directory is `./node_modules/@capacitor-community/firebase-crashlytics/ios/Pods/FirebaseCrashlytics/upload-symbols`. The path to GoogleService-Info.plist relative to the root project directory is probably `./ios/App/App/GoogleService-Info.plist` assuming you put it there.

To find your dSYM path, run `mdfind -name .dSYM | while read -r line; do dwarfdump -u "$line"; done`. Note this may only work after you've forced crash or error.

@priyankpat @danielprrazevedo - You should probably update the documentation to explain this. And if you're too busy to maintain the project, it'd be a nice service to the community to look for some other contributors who aren't.

**Comment by robingenz** [comment] 2021-04-02 15:00
This issue includes several topics. This makes it difficult to handle.
I try to answer all questions and then close this issue. If problems remain, please create a new issue following the bug template.

@essujith I'm using version 0.3.0 in one of my apps. It works fine so far. Please follow the steps in the `README.md` during the installation.
Only `npm install --save capacitor-crashlytics` may not be sufficient.

@Camiloess Please use `FirebaseCrashlytics.recordException` to record non-fatal errors.

@SalahAdDin I have updated all dependencies. Feel free to test the current `dev` version: 
```
npm i @capacitor-community/firebase-crashlytics@0.3.0-dev.24949cd
```

@tnoetzel Thank you for this quick guide. I will update the `README.md`. I also updated the build scripts of the plugin, hoping that the dSYM files are now automatically uploaded during the build.

**Closed as completed by robingenz** 2021-04-02 15:00 UTC
