### ISSUE TITLE
bug: Build Failed after Installing firebase Crashlytics on IOS

### ISSUE THREAD

**Issue by Saqib92** [capacitor-community/firebase-crashlytics#49] opened 2021-10-11 15:02 UTC
**Plugin version:**

`"@capacitor-community/firebase-crashlytics": "^1.1.0",`

**Platform(s):**

`IOS`

**Current behavior:**

Build Failed with an Error:

![Screenshot 2021-10-11 at 7 58 41 PM](https://user-images.githubusercontent.com/7135885/136812732-71d6b49b-cdd8-4350-b8da-d514c2228b14.png)

**Expected behavior:**

Build Should work as Expected

**Steps to reproduce:**

https://github.com/Saqib92/capacitor-firebase-plugins

**Related code:**

```
insert short code snippets here
```

**Other information:**

I am also using Capacitor FCM Push notification might be a conflict in them. 

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/ios: 3.2.4

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2021-10-11 15:20
Thank you for your request.
Can you please share your dependencies (`package.json`)?

**Comment by Saqib92** [comment] 2021-10-11 15:30
```
{
	"name": "my Application",
	"version": "0.0.1",
	"author": "Ionic Framework",
	"homepage": "https://ionicframework.com/",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"build:prod": "ng build --prod",
		"resources": "npx cordova-res android --skip-config --copy",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e"
	},
	"private": true,
	"dependencies": {
		"@angular/common": "~12.0.1",
		"@angular/core": "~12.0.1",
		"@angular/forms": "~12.0.1",
		"@angular/platform-browser": "~12.0.1",
		"@angular/platform-browser-dynamic": "~12.0.1",
		"@angular/router": "~12.0.1",
		"@angular/service-worker": "~12.0.1",
		"@capacitor-community/facebook-login": "^3.1.1",
		"@capacitor-community/fcm": "^2.0.0",
		"@capacitor-community/firebase-crashlytics": "^1.1.0",
		"@capacitor/android": "^3.2.2",
		"@capacitor/app": "^1.0.2",
		"@capacitor/browser": "^1.0.2",
		"@capacitor/camera": "^1.0.3",
		"@capacitor/clipboard": "^1.0.2",
		"@capacitor/core": "^3.2.2",
		"@capacitor/filesystem": "^1.0.2",
		"@capacitor/haptics": "1.0.2",
		"@capacitor/ios": "^3.2.2",
		"@capacitor/keyboard": "^1.0.2",
		"@capacitor/push-notifications": "^1.0.4",
		"@capacitor/share": "^1.0.3",
		"@capacitor/splash-screen": "^1.1.1",
		"@capacitor/status-bar": "1.0.2",
		"@capacitor/storage": "^1.0.3",
		"@ionic-native/app-rate": "^5.34.0",
		"@ionic-native/core": "^5.34.0",
		"@ionic-native/file": "^5.34.0",
		"@ionic-native/file-transfer": "^5.34.0",
		"@ionic-native/image-picker": "^5.34.0",
		"@ionic-native/in-app-browser": "^5.36.0",
		"@ionic-native/media-capture": "^5.34.0",
		"@ionic-native/theme-detection": "^5.36.0",
		"@ionic/angular": "^5.5.2",
		"@ionic/pwa-elements": "^3.0.2",
		"@ng-select/ng-select": "^7.2.0",
		"@types/hammerjs": "^2.0.40",
		"@videojs/themes": "^1.0.1",
		"cordova-plugin-apprate": "^1.7.2",
		"cordova-plugin-dialogs": "^2.0.2",
		"cordova-plugin-file": "^6.0.2",
		"cordova-plugin-file-transfer": "^1.7.1",
		"cordova-plugin-inappbrowser": "^5.0.0",
		"cordova-plugin-media-capture": "^3.0.3",
		"cordova-plugin-nativestorage": "^2.3.2",
		"cordova-plugin-telerik-imagepicker": "^2.3.6",
		"cordova-plugin-theme-detection": "^1.3.0",
		"es6-promise-plugin": "^4.2.2",
		"hammerjs": "^2.0.8",
		"ion2-calendar": "^3.5.0",
		"ionic-rating": "^2.0.0",
		"jetifier": "^2.0.0",
		"moment": "^2.29.1",
		"ngx-file-drop": "^11.2.0",
		"ngx-pinch-zoom": "^2.6.2",
		"ngx-plyr": "^4.0.0",
		"plyr": "^3.6.8",
		"rxjs": "~6.6.0",
		"send-intent": "^2.0.2",
		"tslib": "^2.0.0",
		"zone.js": "~0.11.4"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "~12.0.1",
		"@angular-eslint/builder": "~12.0.0",
		"@angular-eslint/eslint-plugin": "~12.0.0",
		"@angular-eslint/eslint-plugin-template": "~12.0.0",
		"@angular-eslint/template-parser": "~12.0.0",
		"@angular/cli": "~12.0.1",
		"@angular/compiler": "~12.0.1",
		"@angular/compiler-cli": "~12.0.1",
		"@angular/language-service": "~12.0.1",
		"@capacitor/cli": "^3.2.2",
		"@ionic/angular-toolkit": "^4.0.0",
		"@types/jasmine": "~3.6.0",
		"@types/jasminewd2": "~2.0.3",
		"@types/node": "^12.11.1",
		"@typescript-eslint/eslint-plugin": "4.16.1",
		"@typescript-eslint/parser": "4.16.1",
		"eslint": "^7.6.0",
		"eslint-plugin-import": "2.22.1",
		"eslint-plugin-jsdoc": "30.7.6",
		"eslint-plugin-prefer-arrow": "1.2.2",
		"jasmine-core": "~3.7.1",
		"jasmine-spec-reporter": "~5.0.0",
		"karma": "~6.3.2",
		"karma-chrome-launcher": "~3.1.0",
		"karma-coverage": "~2.0.3",
		"karma-coverage-istanbul-reporter": "~3.0.2",
		"karma-jasmine": "~4.0.0",
		"karma-jasmine-html-reporter": "^1.5.0",
		"protractor": "~7.0.0",
		"ts-node": "~8.3.0",
		"typescript": "~4.2.4",
		"video.js": "^7.14.3"
	},
	"description": "An Ionic project"
}

```

**Comment by robingenz** [comment] 2021-10-11 17:22
The dependencies look good. Please create a minimal, reproducible example so I can debug it.

**Comment by Saqib92** [comment] 2021-10-12 08:51
here is the minimal code:
https://github.com/Saqib92/capacitor-firebase-plugins

But I am facing another Issue in this demo repo. Build is Succeeding But firebase have no logs. But in my Actual Project Build is failing.  

For Additional Context my POD file:

```
platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFacebookLogin', :path => '../../node_modules/@capacitor-community/facebook-login'
  pod 'CapacitorCommunityFcm', :path => '../../node_modules/@capacitor-community/fcm'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../../node_modules/@capacitor/clipboard'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/@capacitor/storage'
  pod 'SendIntent', :path => '../../node_modules/send-intent'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
end

```

On Crash facing  error `Thread 4: Fatal error`:
https://github.com/capacitor-community/firebase-crashlytics/blob/faedb0a4edfef83afdc9ad511fa4b6e74405b574/ios/Plugin/FirebaseCrashlytics.swift#L14

**Comment by robingenz** [comment] 2021-10-15 18:49
I need a minimal, reproducible example for the failing build. If the build is successful in your example, then that doesn't help as I can't debug it.
Regarding the missing logs: Please make sure that you have followed the installation instructions correctly and have a look at the following section: [Test your implementation](https://github.com/capacitor-community/firebase-crashlytics#test-your-implementation)

**Comment by Saqib92** [comment] 2021-10-16 05:57
The Issue was Solved by Adding DSYM Script in my Build Phases. 
![Screenshot 2021-10-16 at 10 54 54 AM](https://user-images.githubusercontent.com/7135885/137575627-c16dcf37-dfcf-4cd0-9798-7da95fba06a7.png)


I was Following the Official setup guide but it was causing the issue so i removed Following steps. 
https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading

**Comment by robingenz** [comment] 2021-10-16 08:27
Thanks for the feedback. In this case I will close this issue.

**Closed as completed by robingenz** 2021-10-16 08:27 UTC
Labels: needs: reproduction

**Comment by Saqib92** [comment] 2021-10-16 08:32
But we still need to investigate why this was happening by following Official Setup Guide.

**Comment by robingenz** [comment] 2021-10-16 09:23
Please note the following:

> Important: If you have a bitcode-enabled app that's released to the App Store or submitted to TestFlight, then you need to manually download and provide dSYM files to Crashlytics.

([Source](https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading))

Maybe that was the problem.

If not, please create a new issue with a minimal, reproducible example, because as you said, this is a another issue.
